JDP210601-2
mryndak/project-jdp-2106-01 pull request #1
Opened 2021-06-24 14:28 UTC by mc139

2021-06-24 15:33 UTC, barteknat requested changes

2021-06-24 15:33 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    public GroupDto groupGet() {
jeśli ma to być lista wszystkich grup to typ zwracany List<GroupDto> getGroups, a jeśli jedna grupa to nie ma {"id"} grupy, chociaż trzeba oba te GETy dać, jak również POST i PUT a tego brak

2021-06-24 15:33 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +@RequestMapping("/v1/example")
chyba lepiej ("v1/groups")

2021-06-25 16:13 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    public void createGroup(@RequestBody GroupDto groupDto) {
ogólnie ja bym był za tym, żeby używać skrótowych adnotacji tu @PostMapping - zawsze mniej kodu. I uproszczonych nazw metod na zasadzie np. tu samo "create", bez "group", bo skoro w adresie url jest wskazanie na group no to wiadomo, ze to create odnosi się do grupy produktów a nie do np. produktow, ale to do waszego uznania, albo wskazania przez PMa, mnie po prostu cisnął o to mentor ;)

2021-06-25 16:17 UTC, barteknat commented on .idea/compiler.xml
> +</project>
I pliki z .idea w pull requescie, co nie odnosi się do treści zadania

2021-06-25 17:22 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.DELETE, value = "deleteGroup")
ta metoda chyba niepotrzebna zgodnie z lista endpointow w 25.4 specyfikacja projektu

2021-06-28 14:32 UTC, mryndak reviewed
Do poprawy zgodnie z poprzednimi komentarzami

2021-06-30 16:11 UTC, closed without merging