JDP210601-21: real implementation of ProductController
mryndak/project-jdp-2106-01 pull request #10
Opened 2021-06-30 22:13 UTC by barteknat

2021-07-02 20:29 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
>      @GetMapping("{id}")
Nie działa mi strzelanie postmanem http://localhost:8080/v1/product/1
za to z delete działa i zawraca 200

2021-07-02 21:05 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/service/ProductService.java
> +        return mapper.mapToProductDto(repository.save(mapper.mapToProduct(productDto)));
Return nie zwraca pobranego argumentu, tylko argument zapisany w bazie danych, a jest zmapowany z powrotem na DTO dlatego, ze endpoint wymaga takiego typu.
W metodzie save, która zapisuje obiekt w bazie danych jest mi potrzebna encja, dlatego mapuje argumentDTO na encje, ale w endpoincie w controllerze, gdzie używam serwisu, zwracany jest obiektDTO, dlatego z powrotem mapuje na DTO.

2021-07-02 21:12 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
>      @GetMapping("{id}")
spróbuj tak: najpierw metoda POST żeby dodać obiekt JSON do bazy danych kodilla_project (bez id, bo hibernate generuje automatycznie kolejna wartosc id (pewnie u Ciebie nie jest to już 1 tylko coś tam dalej:)) i dopiero strzelić Postmanem -> GET http:......./product/id obiektu z tabeli products

2021-07-02 21:15 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/service/ProductService.java
> +        return mapper.mapToProductDto(repository.save(mapper.mapToProduct(productDto)));
ogólnie celem było to, żeby mapper działał w serwisie, tak żeby controller był jak najprostszy

2021-07-02 21:16 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/service/ProductService.java
> +        return mapper.mapToProductDto(repository.save(mapper.mapToProduct(productDto)));
ogólnie celem było to, żeby mapper działał w serwisie, tak żeby controller był jak najprostszy

2021-07-02 21:16 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
>      @GetMapping("{id}")
Jest ok :)

2021-07-03 13:55 UTC, piotrek-kuder approved these changes

2021-07-03 17:41 UTC, piotrek-kuder approved these changes

2021-07-05 07:29 UTC, michalswig requested changes

2021-07-05 07:29 UTC, michalswig commented on src/main/java/com/kodilla/ecommerce/controller/ProductController.java
>      @PutMapping(consumes = MediaType.APPLICATION_JSON_VALUE)
Endpoint aktualizuje dane, ale pozwala rowniez na ich dodawanie. Sugeruje zmienic na Patch aby to naprawic.

2021-07-07 12:21 UTC, michalswig approved these changes

2021-07-08 18:44 UTC, merged