JDP210601-14 preview
mryndak/project-jdp-2106-01 pull request #16
Opened 2021-07-05 21:58 UTC by AdrianSkrzypulec

2021-07-06 05:23 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
>      private BigDecimal price;
można  by nazwać listę products albo productList

2021-07-06 05:24 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private List<Product> product;
można by nazwać listę products albo productList

2021-07-06 05:41 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +            mappedBy = "product",
brakuje tabeli łączącej, nie ma ani tutaj ani w encji Product

2021-07-06 09:30 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private List<Product> product;
Racja, poprawie.

2021-07-06 15:44 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private List<Product> product;
jakby coś, to będzie List<CartItem> cartItems po dołożeniu encji CartItem

2021-07-06 15:45 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +            mappedBy = "product",
Adrian, jakby coś to ja dołożę, po dodaniu encji CartItem

2021-07-06 17:11 UTC, barteknat requested changes

2021-07-06 17:11 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +@Table(name = "Cart")
nazwę można by dać "carts" żeby była podobna do reszty encji: produkty, zamówienia, użytkownicy. Można dać w samym @Entity, wtedy @Table jest niepotrzebna

2021-07-06 17:11 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    public List<Product> getProductList() {
ogólnie skoro używamy lomboka i automatycznego gettera w tym przypadku w adnotacji @Date, to nie trzeba ręcznie tworzyć dodatkowego gettera przy ustawianiu relacji, wystarczy dać relacje nad linia 26

2021-07-07 14:39 UTC, michalswig commented
brakuje chyba tylko połączeń z tabelą pomocniczą aby zamknąć ten temat IMHO

2021-07-07 21:01 UTC, barteknat approved these changes

2021-07-07 21:01 UTC, merged

2021-07-07 21:01 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/domain/Cart.java
> +    public List<Product> getProductList() {
Przepisałem  wg. ustaleń

2021-07-07 21:03 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/dto/CartDto.java
> +    private List<Product> product;
@barteknat na razie zakomentowałem i czekam na Twoją encje CartItem