Jdp210601 22
mryndak/project-jdp-2106-01 pull request #18
Opened 2021-07-06 13:15 UTC by mc139

2021-07-06 21:04 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +public interface GroupRepository extends CrudRepository<Group,Integer> {
zamiast CrudRepository można dać JpaRepository

2021-07-06 21:34 UTC, barteknat requested changes

2021-07-06 21:34 UTC, barteknat commented on .idea/.gitignore
> +/httpRequests/
te pliki w sumie trzeba usunac, żeby ich nie mergowac

2021-07-06 21:34 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>      @RequestMapping(method = RequestMethod.GET, value = "getGroups")
może by ujednolicić endpointy? albo dać wszystko skrócone, albo te ogólne

2021-07-06 21:34 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +
metody nadpisane, kontroler repozytorium już je ma defaultowo; u siebie również muszę to poprawić

2021-07-07 08:32 UTC, piotrek-kuder commented on .idea/.gitignore
> +/httpRequests/
prawda, pobrałem ten branch na dysk, nadpisał mi moje pliki w .idea i projekt się nie buduje z zielonego play ;) trzeba z terminala gradlew build

2021-07-07 08:46 UTC, piotrek-kuder requested changes
pliki .idea do usunięcia

2021-07-07 09:11 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +public interface GroupRepository extends CrudRepository<Group,Integer> {
w encji Group id jest typu Long a tutaj jest <Group, Integer>

2021-07-07 11:53 UTC, mc139 commented on .idea/.gitignore
> +/httpRequests/
W Intelijj wyklikałem żeby te pliki sie nie wysyłały ;/ od Teraz będę robił to ręcznie przez git add <adres pliku>

2021-07-07 11:55 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>      @GetMapping("{id}")
Okej dodam slasha:)

2021-07-07 11:57 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>      @RequestMapping(method = RequestMethod.GET, value = "getGroups")
@mryndak @michalswig @mc139 @barteknat @AdrianSkrzypulec co sądzicie ?

2021-07-07 12:40 UTC, michalswig commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>      @RequestMapping(method = RequestMethod.GET, value = "getGroups")
jeśli chodzi o ujednolicenie to bym skróty wszędzie stosował. o slash już było chyba powiedziane

2021-07-07 13:34 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>      @RequestMapping(method = RequestMethod.GET, value = "getGroups")
można dać skrócone jak dla mnie

2021-07-07 14:43 UTC, michalswig commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>              consumes = MediaType.APPLICATION_JSON_VALUE)
IMHO dałbym to consumes na góre klasy zeby przy kazdym endpoincie  nie pisac

2021-07-07 14:59 UTC, piotrek-kuder approved these changes

2021-07-07 18:10 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
>      @RequestMapping(method = RequestMethod.GET, value = "getGroups")
Hej, wydawało mi się, że mamy to ustalone ;)
Skrócone i / tylko przed.

2021-07-08 22:27 UTC, barteknat requested changes

2021-07-08 22:27 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +//    @GetMapping("/{getGroups}")
samo @GetMapping bez nawiasu i jego zawartości

2021-07-08 22:27 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +//    @GetMapping("/{id}")
działa

2021-07-08 22:27 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +//    @PostMapping(
działa

2021-07-08 22:27 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +//    @PatchMapping( value = "/{update}",
samo @PatchMapping(consumes = MediaType.APPLICATION_JSON_VALUE)

2021-07-08 22:27 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/service/GroupService.java
> +    @Transactional
@Transactional Mateusz mówił żeby dać w GroupRepository

2021-07-09 09:05 UTC, michalswig approved these changes

2021-07-09 14:51 UTC, barteknat approved these changes

2021-07-09 16:25 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/repository/GroupRepository.java
> +
metody List<Group> findAll() i Group save(Group group) można usunąć z GroupRepository, bo one sie juz w takiej formie znajdują w CrudRepository i są przez niego udostępniane; można z nich skorzystać bezpośrednio wywołując je przez obiekt typu interfejsowego GroupRepository; metody groupById(long id) i deleteById(long id) również się znajdują w tym interfejsie, ale one muszą tu zostać, bo defaultowo przyjmują argument typu Integer, a ze my korzystamy z longa, bo id może być większe niż jest w stanie obsłużyć Integer (no może nie akurat w przypadku grup produktów), to musimy napisać je jakby nowe bo z innym typem argumentu. Tzn ja to tak rozumiem

2021-07-09 21:46 UTC, AdrianSkrzypulec approved these changes

2021-07-10 19:37 UTC, merged