Jdp210601 5
mryndak/project-jdp-2106-01 pull request #3
Opened 2021-06-25 16:43 UTC by barteknat

2021-06-25 17:27 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +    //private final UserMapper userMapper;
Mapper dla Usera powinien być w klasie UserService jako, że z controllera powinnna być wyrzucona cala logika, w myśl ze controller ma być fasadą.

2021-06-25 17:27 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +
a inne metody

2021-06-29 09:48 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +    public ResponseEntity userLogin(@RequestBody Map<String, String> creds){
pytanie czy nie lepiej byloby dac w argumencie: @RequestBody UserDto user zamiast mapy (dlatego ze podajemy body jako obiekt JSON) i pozniej np w serwisie walidacja czy jest taki user w List<User> users a nie mapie? I od tej walidacji uzaleznione generowanie klucza? jak myslicie

2021-06-29 15:16 UTC, mc139 requested changes
Myślę że User ID nie będzie przechowywane w bazie danych jako String, nie sądzisz ze lepiej było by zmienić typ na np. Long ?

2021-06-29 15:16 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +    public ResponseEntity blockUser(@RequestBody String id){
Myślę że User ID nie będzie przechowywane w bazie danych jako String, nie sądzisz ze lepiej było by zmienić typ na np. Long ?

2021-07-01 09:56 UTC, michalswig commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +    public ResponseEntity blockUser(@RequestBody String id){
podałem Stringa, żeby obsłuzyć requestbody, które jest tekstem, potem parsuje to do Longa.

2021-07-01 09:58 UTC, michalswig commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +    //private final UserMapper userMapper;
OK usunę L17

2021-07-01 09:59 UTC, michalswig commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +    public ResponseEntity userLogin(@RequestBody Map<String, String> creds){
uzyłem mapy, bo Dto posiada dodatkowe pola, których tu nie potrzebuje. Mapa powinna być szybsza.

2021-07-01 11:26 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +        System.out.println("id: " + userDto.getId() + ", name: " + userDto.getUserName() + " was created");
Michał, metoda getUserName ma Name z duzej, powinna byc getUsername zgodnie z polem w UserDto; powoduje to blad w budowaniu aplikacji przez co nie przeszedl test narzedzia circleci. Sprobuj zmienic nazwe

2021-07-01 15:42 UTC, michalswig commented on src/main/java/com/kodilla/ecommerce/controller/UserController.java
> +        System.out.println("id: " + userDto.getId() + ", name: " + userDto.getUserName() + " was created");
poprawiłem zgodnie

2021-07-01 15:42 UTC, michalswig approved these changes

2021-07-02 13:26 UTC, mc139 approved these changes

2021-07-02 19:38 UTC, AdrianSkrzypulec approved these changes

2021-07-02 21:27 UTC, merged