JDP210601-4 and JDP210601-29 - adding OrderController temporary imple…
mryndak/project-jdp-2106-01 pull request #5
Opened 2021-06-26 15:54 UTC by piotrek-kuder

2021-06-26 22:36 UTC, barteknat requested changes

2021-06-27 06:16 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +@RequestMapping(value = "/v1/order", consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE)
- moim zdaniem produces i consumes lepiej zostawić, za jakiś czas my albo ktoś będziemy się zastanawiać co metoda przyjmuje: json, xml, text a może jeszcze co innego
- consumes przeniosłem w klasach OrderController i od razu w ProductsController

2021-06-27 06:16 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    @DeleteMapping
zrobione

2021-06-27 06:22 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    public OrderDto createOrder(@RequestBody final OrderDto orderDto) {
będzie to w czymś przeszkadzać w przyszłości? zmienna final ma przypisaną wartość w momencie utworzenia, w tym przypadku to się może przydać

2021-06-27 08:40 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +@RequestMapping(value = "/v1/order", consumes = APPLICATION_JSON_VALUE, produces = APPLICATION_JSON_VALUE)
- consumes jak najbardziej, ale przy endpointach przy których jest potrzebne, a nie nad klasa. Nie jestem pewien co do produces no ale to może później wyjdzie faktycznie ze jest potrzebne, no bo przecież niby z automatu dostajemy zwrot w formie JSONa.
- jeśli chodzi o klasę ProductsController, która jako przyklad jest na masterze, to nie musisz tu nic zmieniać, bo jak zająłem się w ramach swojego taska klasą ProductController (bez "s" tak żeby nasze kontrolery były spójne nazwami), to nie przerabiałem tej przykładowej, tylko zrobiłem od nowa, a przykładową usunąłem; także po mergu z masterem pull requesta JDP210601-1, klasa ProductsController zostanie usunięta, a dodana ProductController.
Poza tym od razu byłyby konflikty po naszych mergach :D

2021-06-27 09:24 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    public OrderDto createOrder(@RequestBody final OrderDto orderDto) {
nie przeszkadzać, tylo raczej zbędne, argument i tak ma swoją wartość w momencie utworzenia, a final powoduje ze nie można przypisywać mu nowej wartości w samej metodzie, tylko ze tu odnosi się do referencji obiektu nie czyniąc samego obiektu niemutowalnym, czyli pola tego obiektu i tak można zmieniać

2021-06-27 09:24 UTC, barteknat approved these changes

2021-06-27 10:52 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/OrderController.java
> +    public OrderDto createOrder(@RequestBody final OrderDto orderDto) {
masz na myśli, że jest zbędne, czy że nie jest niezbędne? bo że nie jest niezbędne to się zgadzam
o to chodzi z final, referencja zawsze będzie wskazywać na ten sam obiekt
zastosowanie final nie powinno powodować żadnych problemów, a może potencjalnie zapobiec problemom
tak na dobrą sprawę słowo final by mogło w javie nie istnieć, tak samo private - programista by sam pilnował zasięgu zmiennych i metod

2021-07-01 14:54 UTC, mc139 approved these changes

2021-07-02 06:22 UTC, merged