Jdp210601 13
mryndak/project-jdp-2106-01 pull request #8
Opened 2021-06-28 13:29 UTC by mc139

2021-06-28 14:20 UTC, barteknat requested changes

2021-06-28 14:20 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.DELETE, value = "deleteGroup")
brakuje endpointa POST, a DELETE niepotrzebny:

groups (grupy produktów):
lista wszystkich grup
dodanie grupy
wyświetlenie grupy o podanym id
aktualizacja wybranej grupy

2021-06-28 14:20 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "updateGroup")
brakuje consumes

2021-06-28 14:20 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "updateGroup")
chociaz chyba byl bo w importach jest MediaType :)

2021-06-29 12:43 UTC, mc139 reviewed
Hej, mógłby ktoś z Was na ten commit rzucić okiem ?

2021-06-29 12:44 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "updateGroup")
juz naprawione:)

2021-06-29 17:17 UTC, barteknat requested changes

2021-06-29 20:48 UTC, barteknat requested changes

2021-06-29 20:48 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getGroup")
nie działa mi ta metoda, zadziałała jak zmieniłem na prostsza implementacje: 
    @GetMapping("{id}")
    public GroupDto getGroup(@PathVariable long id) {
        GroupDto groupDto = new GroupDto();
        groupDto.setName("Test One Group");
        groupDto.setId(1);
        return groupDto;
    }
reszta działa, ale skomplikowana implementacja

2021-06-29 20:48 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +public class GroupController {
klasa nie z tego pull requesta, przynależy do JDP210601-2

2021-06-29 20:48 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    @NotNull
@NotNull jest chyba niepotrzebne, dlatego ze @Id gwarantuje notnull i uniqueness, ale to PM jakbyś mógł się wypowiedzieć

2021-06-29 20:48 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    @Column(name = "ID")
to niepotrzebne, bo Hibernate stworzy defaultowo kolumnę w tabeli na podstawie nazwy pola; także kolumna będzie się i tak nazywała "id"

2021-06-29 20:48 UTC, barteknat commented on .idea/.name
> +ecommerce
pliki z .idea utrudniają czytanie pull requesta tego i JDP210601-2

2021-06-29 20:48 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +@Entity(name = "Group")
chyba niepotrzebne, bo encja i tak zostanie nazwana group z automatu

2021-06-30 05:48 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +@Entity(name = "Group")
MySQL nie puści Wam nazwy encji group. Powinien wywalić jakiś błąd przy uruchamianiu.

2021-06-30 05:49 UTC, mryndak commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +@Entity(name = "Group")
Należy zmienić nazwę encji

2021-06-30 12:54 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +public class GroupController {
Przypadkowo usunąłem dwie metody, po czym to naprawiłem i zpushowałem jednym commitem na tym samym branchu;/

2021-06-30 12:55 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    @NotNull
@mryndak co sądzisz?

2021-06-30 12:59 UTC, mc139 commented on .idea/.name
> +ecommerce
Okej dzięki za uwagę przy nastepnych commitach sprawdzę to jeszcze raz czy się przypadkowo nie dodają (git status), oczywiście folder .idea mam w gitignore, ale nie rozumiem jeszcze czemu dalej się dodają

2021-06-30 13:02 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +@Entity(name = "Group")
@mryndak mógłbyś trochę bardziej szczegółowo to wytłumaczyć tj. na jaka nazwę to zmienić, faktycznie wywala błędem :)

2021-06-30 13:10 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +@Entity(name = "Group")
Na inną, nie może się nazywać Group bo ta nazwa jest zarezerwowana. Może być ProductGroup

2021-06-30 13:56 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getGroup")
chodzilo mi wlasnie o implementacje @RequestParam, bo dluzsza i bardziej skomplikowana od tych skrotowych endpointow. Jesli chodzi o uporzadkowanie i np o jakie id chodzi, to sie nie zgodze, z uwagi na to ze w skrotowych kod sie sam tlumaczy, tu: public GroupDto getGroup(@PathVariable long id) -> metodo getGroup zwroc obiekt GroupDto o id ... . Pozniej tego url i tak nigdzie nie bedzie sie wpisywalo, tylko bedzie to za nas robil front, czy jakas aplikacja inna.
Jesli chodzi o dzialanie, przepraszam, ale faktycznie zle dalem nazwe :) jest git!

2021-06-30 14:01 UTC, barteknat commented on .idea/.name
> +ecommerce
no to git add *sciezka do konkretnego pliku* :) jakbys prawym kliknal na klase na drzewku po lewej to jest opcja do skopiowania sciezki, co mozna wkleic po gid add

2021-06-30 14:14 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +@Entity(name = "Group")
Dzięki @AdrianSkrzypulec  już zmieniłem, będzie ProductGroup w następnym commicie :)

2021-06-30 14:23 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getGroup")
Z mojej strony nie ma problemu żeby to zmienić, aczkolwiek należy się zastanowić czy optymalnie jest mieć krótszy kod ("@GetMapping"), czy może ujednolicone endpointy ("@RequestMapping(method = RequestMethod.GET, value = "getGroup")") @mryndak @michalswig @barteknat @AdrianSkrzypulec co sądzicie ? 
Ogólnie zgadzam się z Tobą @barteknat, ale niech reszta naszego teamu się też wypowie w tej kwestii, zmiany zpushuję w następnym commicie :)

2021-06-30 14:25 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getGroup")
Jasna sprawucha 🙂

2021-06-30 14:25 UTC, mc139 commented on .idea/.name
> +ecommerce
Dzięki @barteknat "Keep It Simple, Stupid" nawet w przypadku git'a się sprawdza 😃

2021-06-30 19:53 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getGroup")
Hej,  ja też w swoim zmieniłem na skróconą formę "@GetMaping" jest przejrzyściej i będzie spójne w przykładowym kontrolerem.

2021-06-30 19:55 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    @Column(name = "ID")
Nie jest potrzebne, ale też nie przeszkadza, mnie wygodniej jest czytać taki kod.

2021-07-01 07:45 UTC, piotrek-kuder approved these changes

2021-07-01 12:24 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getGroup")
a więc ustalone :)

2021-07-01 16:25 UTC, barteknat requested changes

2021-07-01 16:25 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @GetMapping("{id}")
jak dla mnie to albo wszystkie, albo żadna :P

2021-07-01 16:25 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    @Id
powinno być @GeneratedValue, żeby Hibernate nadawał kolejny nr id

2021-07-01 20:10 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @GetMapping("{id}")
Od jakiejś trzeba zacząć ;)

2021-07-01 20:22 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/dto/GroupDto.java
> +    private int id;
żeby było konsekwentnie można zmienić int na long

2021-07-01 20:48 UTC, AdrianSkrzypulec commented
Kod się buduje, strzelanie postmanem działa prawidłowo.

2021-07-02 13:03 UTC, mc139 commented on src/main/java/com/kodilla/ecommerce/controller/GroupController.java
> +    @GetMapping("{id}")
Hej w ciele metody getGroups() stworzyłem jako zaślepkę tamte trzy groupDto zeby można było z Postmana sprawidzić czy wszystko działa- na dalszym etapie tego juz nie bedzie :)

2021-07-02 19:35 UTC, AdrianSkrzypulec approved these changes

2021-07-03 06:07 UTC, michalswig commented on src/main/java/com/kodilla/ecommerce/domain/Group.java
> +    @NotNull
@id IMHO nie sprawdza null`i, ale np @GeneratedValue już nulla wyklucza i wtedy walidacji @notnull nie trzeba używać, natomiast para @id @not null w mojej opinii nie jest nadmiarowa.

2021-07-03 07:07 UTC, merged