JDP210601-3 CartController v3 to review
mryndak/project-jdp-2106-01 pull request #9
Opened 2021-06-30 19:30 UTC by AdrianSkrzypulec

2021-06-30 20:08 UTC, barteknat approved these changes

2021-07-01 07:08 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
w jaki sposób można będzie dodać kilka produktów?

2021-07-01 07:23 UTC, piotrek-kuder requested changes
komentarz pod linią 46

2021-07-01 07:56 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
Założyłem, że dla uproszczenia produkty będą dodawane po jednej sztuce, mogę dodać "int quantity"

2021-07-01 08:07 UTC, barteknat commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
Dodawane są do listy, czyli może list.size()

2021-07-01 08:58 UTC, AdrianSkrzypulec commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
To jest dobry pomysł i nie wymagał by dodawania kolejnego pola.

2021-07-01 09:01 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
>      public void makeOrder(@RequestBody final ExampleDto orderDto) { //finalnie OrderDto
jestem na etapie tworzenia klas Order i utknąłem na pobieraniu listy List<OrderItem> Items, obliczaniu totalPrice i powiązaniem między klasami Order i Cart.
W specyfikacji w rozdz.25 jest przy cart:  "utworzenie zamówienia na podstawie koszyka",
a przy order: "dodanie nowego zamówienia"

Jak dla mnie wychodzi, że List<OrderItem> Items powinno być w koszyku cart a nie w Order oraz cart liczy totalPrice i przekazuje w JSON id koszyka, listę OrderItem i wartość koszyka a klasa orderController na podstawie koszyka i danych użytkownika dodaje do bazy nowe zamówienie - coś na tej zasadzie.
Diagram ERD, który teraz mamy jest wg mnie w sobotę do uzupełnienia.

2021-07-01 09:02 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
zobacz komentarz niżej

2021-07-01 09:07 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
>      public void makeOrder(@RequestBody final ExampleDto orderDto) { //finalnie OrderDto
albo może ktoś ma inny pomysł jak połączyć Order i Cart, bo w obecnej postaci nie wiem skąd pobrać List<OrderItem> items

2021-07-01 09:16 UTC, piotrek-kuder commented on src/main/java/com/kodilla/ecommerce/controller/CartController.java
>      public void makeOrder(@RequestBody final ExampleDto orderDto) { //finalnie OrderDto
może mapper na podstawie user i cart zrobi orderDto?

2021-07-02 06:34 UTC, piotrek-kuder approved these changes

2021-07-02 07:21 UTC, merged